### ISSUE TITLE
Including identity cache in a base model that other models inherit from causes issues

### ISSUE THREAD

**Issue by johnkelly** [Shopify/identity_cache#182]
Ran into the issue where if a model inherited a base model that included Identity Cache the secondary indexes would be shared across models generating undefined method errors. The offending line was line 15 of configuration dsl which create the cache_indexes array on the class that includes identity cache (ModelBase in this case).

https://github.com/Shopify/identity_cache/blob/master/lib/identity_cache/configuration_dsl.rb#L15
````ruby
class ModelBase < ActiveRecord::Base
  include IdentityCache
end

class User < ModelBase
    cache_index :user, :key
end

class Store < ModelBase
    cache_index :store, :id
end
````

I resolved the error by including Identity Cache individually on all models and not on a base model.

**Comment by waheedel** [comment]
Ran into this issue as well while using the same index on 2 inherited models.
```ruby
class Model < ActiveRecord::Base
...
class ModelA < Model
  cache_index :column_a, :column_b
...
class ModelB < Model
  cache_index :column_a, :column_b

ModelA.create!(column_a: 1, column_b: 1)
ModelB.create!(column_a: 1, column_b: 1)

ModelA.fetch_by_column_a_and_column_b(1, 1).pluck(:type)
=> ['ModelA']
ModelB.fetch_by_column_a_and_column_b(1, 1).pluck(:type)
=> ['ModelA']

Rails.cache.clear

ModelB.fetch_by_column_a_and_column_b(1, 1).pluck(:type)
=> ['ModelB']
ModelA.fetch_by_column_a_and_column_b(1, 1).pluck(:type)
=> ['ModelB']
...
```

[This](https://github.com/Shopify/identity_cache/blob/dbfebba84a72e94ad9b922ffebbc71ac749b47df/lib/identity_cache/cache_key_generation.rb#L39) line creates a cache key `=> 'IDC:5:index:Model:column_a/column_b:2924373911532578698'` where 2924373911532578698 is a hash of the values `'1/1'`. 

How about using `name` instead of `base_class.name` which would generate `'IDC:5:index:ModelA:column_a/column_b:2924373911532578698'` and `IDC:5:index:ModelB:column_a/column_b:2924373911532578698'` and allow for fetching by subclass.

**Comment by dylanahsmith** [comment]
> I resolved the error by including Identity Cache individually on all models and not on a base model.

Yes, that is the way it is meant to be used.  `include IdentityCache` sets up that model for caching, including adding an after_commit callback to expire the cache when it changes.  We don't have any plans to make this work for all/most models by just including it into a abstract base class.

Perhaps we should make these class methods raise if called on anything but the base class to make this more explicit.
