### ISSUE TITLE
use pagination with identity cache

### ISSUE THREAD

**Issue by MZainDamlag** [Shopify/identity_cache#237]
Hello

I have a problem in applying cache with pagination, for example:

paginate Product.fetch(params[:id]).fetch_images

so it always go to database although it hit the product in the cache but not images

**Comment by dylanahsmith** [comment]
Right now `fetch_images` is returning a loaded association, so calling relation methods on it will result in a cache fetch as well as a database query.  Identity cache just stores the whole relation as a blob, so it doesn't make sense to cache an association that requires paginating, since it will load the whole association to fill the cache.

I plan on making `fetch_images` return an array in this case, in pull requset https://github.com/Shopify/identity_cache/pull/224, since that will avoid this misuse of identity cache.

**Comment by MZainDamlag** [comment]
what if I want to use IDC with with globalize gem to cache the translation tables wit the entities

**Comment by dylanahsmith** [comment]
I'm not familiar with that gem, but IdentityCache is meant to be opt-in caching, so if the gem does the database querying, then IdentityCache won't automatically cache those queries.

I'm going to close this issue, since pagination is out of scope for identity cache.
