### ISSUE TITLE
Q: Opt-in to always use IdentityCache with original method?

### ISSUE THREAD

**Issue by elado** [Shopify/identity_cache#284]
Is there an option to have the original method of an association go through `identity_cache`?

I want some mostly-static models, e.g. `Category` to always be read from cache even when I access `product.category`, and not only `product.fetch_category`.

**Comment by dylanahsmith** [comment]
No.

* We don't want to implicitly use the cache because we don't want cache corruption getting persisted.  That still applies to the rare cases where you do update that model
* has_one and has_many association methods return a relation that can be used to build a query, but the IDC method just returns that record or an array of records
