### ISSUE TITLE
Ability to explicitly invalidate IDC keys

### ISSUE THREAD

**Issue by sgringwe** [Shopify/identity_cache#289]
I have a few hotspots in my code where I'd like to use update_columns, but that does not call callbacks to invalidate IDC. For now I'm calling update, but that's extra work that I'd like to avoid in these particular code paths. Is there any way to explicitly invalidate the cache keys for IDC? I found some relevant code in the repo, but it's private methods. Would a PR to make them public be accepted?

**Comment by camilo** [comment]
👎 on making explicit expiration a common op, we have internally debated this and my argument has always been "if the cache needs manual expiration, that is either a bug we need to fix or we are using it where it does not belong".

If you must, for say broken data due to a bug you can `send :expire_cache` to the AR objects.

**Comment by sgringwe** [comment]
Fair enough, thanks for the response.
