### ISSUE TITLE
cache_belongs_to not respecting the scope

### ISSUE THREAD

**Issue by jeffblake** [Shopify/identity_cache#304]
I have something like this

```
class Variant
  belongs_to :product, -> { with_deleted }
  cache_belongs_to :product
end
```

`with_deleted` is a scope provided by the Paranoia gem. 

calling `variant.product` triggers the query
`SELECT  "products".* FROM "products" WHERE "products"."id" = $1 LIMIT $2  [["id", 1178], ["LIMIT", 1]]`

where calling `variant.fetch_product` queries
`SELECT  "products".* FROM "products" WHERE "products"."deleted_at" IS NULL AND "products"."id" = $1 LIMIT $2  [["id", 1178], ["LIMIT", 1]]`

I would expect that `fetch_product` uses the unscoped query, like calling `.product`

**Comment by joshaidan** [comment]
I think that would be the expected behaviour. `fetch_product` is returning all the products that have not been deleted (i.e. where deleted_at is NULL). When you're calling `.product` it's returning all products, even the deleted ones. (this is the with_deleted scope) 

The `-> { with_deleted }` scope is not being applied to the `cache_belongs_to` fetch method--which I think is expected.

**Comment by joshaidan** [comment]
Oh, but I think this might be a situation where it gets interesting:

```
2.2.5 :001 > v = Variant.new
 => #<Variant id: nil, product_id: nil, created_at: nil, updated_at: nil>
2.2.5 :002 > v = Variant.first
  Variant Load (0.3ms)  SELECT  "variants".* FROM "variants" ORDER BY "variants"."id" ASC LIMIT ?  [["LIMIT", 1]]
 => #<Variant id: 1, product_id: 1, created_at: "2017-02-17 23:38:13", updated_at: "2017-02-17 23:38:13">
2.2.5 :003 > v.product
  Product Load (0.2ms)  SELECT  "products".* FROM "products" WHERE "products"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
 => #<Product id: 1, created_at: "2017-02-17 23:38:02", updated_at: "2017-02-18 06:49:18", deleted_at: "2017-02-18 06:49:13">
2.2.5 :005 > v.fetch_product
 => #<Product id: 1, created_at: "2017-02-17 23:38:02", updated_at: "2017-02-18 06:49:18", deleted_at: "2017-02-18 06:49:13">
```

Notice on the last call to `v.fetch_product` it hits the cache and returns a result. Where if I were to call `v.fetch_product` without first calling `v.product` you get:
```
2.2.5 :001 > v = Variant.first
  Variant Load (0.3ms)  SELECT  "variants".* FROM "variants" ORDER BY "variants"."id" ASC LIMIT ?  [["LIMIT", 1]]
 => #<Variant id: 1, product_id: 1, created_at: "2017-02-17 23:38:13", updated_at: "2017-02-17 23:38:13">
2.2.5 :002 > v.fetch_product
  Product Load (0.1ms)  SELECT  "products".* FROM "products" WHERE "products"."deleted_at" IS NULL AND "products"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
[IdentityCache] cache miss for IDC:7:blob:Product:12179499797021229948:1
 => nil
```
It misses the cache and runs the query with `deleted_at IS NULL`. So you get contradictory behaviour. One case where it will return a result, and one case where it does not.

I'm not a project maintainer so I couldn't tell if you there was a reason for this behaviour.

**Comment by dylanahsmith** [comment]
I think originally the scopes weren't thought of as much and it was only later that we started to add some checks to make sure fetch_ methods weren't called with an added scope (e.g. https://github.com/Shopify/identity_cache/pull/217).

I agree that this is definitely a bug, since different results are returned based on whether it is a cache hit or miss.  However, I think the "solution" would be to not support this type of association by checking for the scope and raising an exception when `cache_belongs_to` is called referencing this type of association.  That would at least avoid confusion and hopefully prevent bugs from trying to do something like this from making it into production.

Actually supporting this wouldn't be trivial, since we would have to fetch records unscoped when `fetch_by_id` is called on a model, then check the scope in order to determine if the record should be filtered.  In your use case, currently `Variant.fetch_product` uses `Product.fetch_by_id` to fetch the record using the default scope on Product, so soft-deleted records would result in `nil` being stored in the cache for that product id.

For your case, is fetching a deleted product a common enough use case that it is necessary to use identity_cache to fetch it?  Because I would be hesitant about adding supporting for a use case that is an premature optimization.

**Comment by jeffblake** [comment]
Well in this particular case, it doesn't make sense to have an undeleted variant with a deleted product, but I have other classes where I use

`delegate :whatever, to: :fetch_whatever_relation`

Given that, `:whatever` should return the same thing whether its called on `whatever_relation` or `fetch_whatever_relation`

I think you could support it pretty easily by adding 
`Product.unscope(where: :deleted_at)` when calling `Product.fetch_by_id`
And for those who don't have a deleted_at column, its silently ignored.

**Comment by dylanahsmith** [comment]
Identity cache respects the default scope on the model just fine, which works for soft-deletion.  This issue is limited to additional scopes added by the belongs_to association (e.g. `belongs_to :product, -> { with_deleted }` to override the default scope).

I don't really think it makes sense to hard code behaviour for soft-deletion, since it doesn't seem like getting soft-deleted data is likely to be a bottleneck that requires caching.
