### ISSUE TITLE
Should I use fetch_multi or where(id: ids)

### ISSUE THREAD

**Issue by xuxiangyang** [Shopify/identity_cache#321]
Hi，I found that if I select 200 recordings from database. it spend 54.869ms with `fetch_multi`, but it only cost 0.561 with `where(id: ids)`;

here is my code

```ruby
ids = [] # id array which length is 200

a= Time.now; User.fetch_multi(ids); b = Time.now; puts b - a # run many times it  puts 0.054869

a= Time.now; User.where(id: ids); b = Time.now; puts b - a # run many times it  puts 0.000561

```

should I use fetch_multi in this case ? Or what is the using case with fetch_multi?

**Comment by dylanahsmith** [comment]
It sounds like `fetch_multi` might be slower because it is a cache miss.  It could also be from errors in making requests to the memcache server.

How many cached associations/indexes/attributes do you have on the `User` model? Since that will increase how much data is stored in and loaded from the cache.  This will further add to how slow `User.fetch_multi` will be on a cache miss, since it will make multiple database requests to fill the cache.

**Comment by xuxiangyang** [comment]
It does not make great improvement after remove  cached associations/indexes/attributes. here is the log
![image](https://cloud.githubusercontent.com/assets/4926529/23289375/23620324-fa84-11e6-9be5-080b04ac2604.png)
In my understanding, Identity cache would make 200 times cache read, so it is slower than raw `where`, right?
so, I should use `where(id: ids)`

**Comment by dylanahsmith** [comment]
```ruby
a= Time.now; User.where(id: ids); b = Time.now; puts b - a
```

Active record queries are lazily performed, so that doesn't actually execute the query.  Use `.to_a` to cause the query to be executed (i.e. `User.where(id: ids).to_a`)

**Comment by xuxiangyang** [comment]
result like this

```ruby
a = Time.now; 100.times {User.where(id: ids).to_a}; b = Time.now; b - a => 0.715387
a = Time.now; 100.times {User.where(id: ids).to_a}; b = Time.now; b - a => 2.834859
```

**Comment by dylanahsmith** [comment]
Why would benchmarking the same code twice produce different results?

**Comment by xuxiangyang** [comment]
sorry, copy error....
