### ISSUE TITLE
Cache the blob on the application server?

### ISSUE THREAD

**Issue by simon-shopify** [Shopify/identity_cache#347]
With the way memcached distributes the blobs on different its ring (in that the right term?), a specific blob will always be on a single machine. We noticed some memcached requests take 3 orders of magnitude more time when a row is _very_ hot because all the load goes on the same server.

I was wondering if it is a good idea to retain certain blobs in the IDC client for very short amounts of time (1 s for instance) to save requests when a row is hot? Afaik, invalidation is made in an after commit, so we already have a small window where inconsistencies are possible between the instant the transaction is commited and the write to memcached completes. It would increase this window by a lot, from tens of µs to let's say 1 s, so maybe we only do this local caching if we detect the kind of access patterns as described above? Maybe we could refill this cache with a very low timeout for the memcached call so we fail fast when the server is under load?

What do you think?

cc: @csfrancis

**Comment by csfrancis** [comment]
This seems reasonable to me - is there any reason why you think this couldn't work @dylanahsmith, @fbogsany ?

**Comment by dylanahsmith** [comment]
> We noticed some memcached requests take 3 orders of magnitude more time when a row is very hot because all the load goes on the same server.

What do you mean by the row being very hot?  If it is just because of a lot of read requests to it, then it doesn't sound like what you are proposing would help.  So it sounds like maybe you mean that the cache entry is being frequently read and written to, but some clarification would be nice.

I'm also curious about whether the memcached performance problems are from the number of operations on keys or whether the size of those keys is causing a significant problem.  Since normalizing our cache blobs would mean that we would expire and write smaller cache blobs, which could help if the size of the cache blobs are a problem, but would aggravate the problem if the problem is with the number of keys being operated on due to the need to fetch more keys per request.

If the problem is with the writes requests, then is this a case that could be improved by normalizing the cache keys more.

> I was wondering if it is a good idea to retain certain blobs in the IDC client for very short amounts of time (1 s for instance) to save requests when a row is hot?

1 seconds isn't a very short amount of time when it comes to computers and it isn't clear to me how you are going to determine that the row is "hot" to do this conditionally as you are implying.  It is common for clients to try to read their own writes, such as when a POST request receives a redirect response to a page that shows the result.  This is also concerning since we still use `IdentityCache.fetch_read_only_records = false` in Shopify.

I would prefer if the cache fetch was explicit about its tolerance to stale data.  We do the same thing when we read from the mysql read slave to avoid similar problems.

**Comment by simon-shopify** [comment]
> What do you mean by the row being very hot? If it is just because of a lot of read requests to it, then it doesn't sound like what you are proposing would help. So it sounds like maybe you mean that the cache entry is being frequently read and written to, but some clarification would be nice.

Yes, what I was proposing was to "debounce" reads on a per-host basis.

> It is common for clients to try to read their own writes, such as when a POST request receives a redirect response to a page that shows the result. This is also concerning since we still use IdentityCache.fetch_read_only_records = false in Shopify.

This suggestion was more of an easy workaround until we can better handle large volumes of reads. However you are right that we do risk of losing the property of reading your own writes if you hit another server (very likely) that recently read that record (more or less likely depending on the data). I don't see an easy way to mitigate this problem, so I'll close this issue.

**Comment by alexsnaps** [comment]
We're thinking about this for `Shop` more specifically.
The idea would be to have a given lookup for `Shop` (given its large payload in memcached) be lookable with "lower" consistency guarantees from the storefront. We could have a in-memory cache that only starts populating after `n` misses, where cache entries are TTL'ed. So that only if you hit a certain rate, the local cache is effectively being used to store `Store` instances. TTL also still guarantees eventual freshness of the data. 
Eviction would be LFU-based, so that "noise traffic" to other stores don't impact the actually hot `Store`. This should be implementable with low overhead, as this probably wouldn't be used outside of traffic spikes to a given shop's storefront, currently mostly associated with flash sales... Which would reduce the impact on memcached these flash sales currently have.

**Comment by alexsnaps** [comment]
Duh! wrong repo…
