### ISSUE TITLE
Error when fetching nil values

### ISSUE THREAD

**Issue by Messinger** [Shopify/identity_cache#350]
I'm not able searching for entries which should have a `nil` as value.

Have a model `VendorSetting` with columns `vendor`,`keyname`, `value`, `languagecode`

Due limitations of oracle (it isn't able storing empty strings and convert them to nil) we have to search for not set languagecode this way:

```
VendorSetting.find_by :vendor => 1, :keyname => 'targethost', :languagecode => nil
```
which will return a correct entry.
Searching for 
```
VendorSetting.find_by :vendor => 1, :keyname => 'targethost', :languagecode => ''
```
fails 'cause oracle doesn't store empty strings and always convert them.

But using your'e (very nice) cache in that case, eg.,

```
VendorSetting.fetch_by_vendor_and_keyname_and_languagecode 1,'targethost',nil
```
will return nothing (but would be found with `find_by`), trying empty string for languagecode (of course) same.

I didn't debug into but it seems that you filter out `nil` as search value anywhere what IMHO isn't correct - sometimes values ARE `nil` (not just in that example or with oracle as backend)

May you check and fix this? IMHO this is not a trivial workflow bug....

**Comment by dylanahsmith** [comment]
It looks like our cache key generation for cache index methods (i.e. fetch_by_*) just use `values.join('/')` on the raw values, which can result in different values to map to the same cache key.  This is bad because a `VendorSetting.fetch_by_languagecode('')` and `VendorSetting.fetch_by_languagecode(nil)` would use the same key, causing the former cache a result used by the latter even though they would result in a different results, since Array#join calls `to_s` on the values and `nil.to_s` becomes `''`.

Could you try clearing the cache then try `VendorSetting.fetch_by_vendor_and_keyname_and_languagecode 1,'targethost',nil` twice to see if it then provides the right value for the cache miss and cache hit?  That would help confirm my hypothesis about what is causing your problem.

Unfortunately, we may also be relying on this behaviour in a subtle way when active record would coerce the value before performing the query.  The problem is that by changing `values.join('/')` to something like `values.map(&:inspect).join('/')` to avoid caching results from one query then using them for another query, then we could end up not expiring a cache key when a row changes if the values were coerced by active record.  For example, if `Product.fetch_by_vendor(:foo)` used `:foo` in the cache key for the provided value then active record coerces the symbol to a string based on the column type, then the cache key wouldn't be invalidated when the row is updated, since it would instead use `"foo"` in the cache key during cache invalidation.  We should be coercing the provided values based on their column type before creating the cache key.

**Comment by Messinger** [comment]
Ok.

did it.

and I'm not kidding you: it doesn't happen anymore. Not sure whats the reason, I'd tried it hours today. This moment I have just debugging access on console, next days I'll run whole application again within debugger and check whats happen.

But so - I think the problem isn't on your side. May I saw the effect due a corrupt database or something like that.

Sorry and tnx for your fast answer.

**Comment by dylanahsmith** [comment]
I've opened https://github.com/Shopify/identity_cache/issues/352 to track the issues I found.  Let me know if you end up determining that it was the cause of you issue.
