### ISSUE TITLE
Fetch by secondary index returns array instead of active record collection

### ISSUE THREAD

**Issue by matthu24** [Shopify/identity_cache#398]
When querying on a field that is meant to return a collection of records, `fetch_by_field_name` returns an array class instead of an active record collection.  I don't see much documentation on how this should behave, but it would be nice if this would work more like a `where` query.  Returning an array makes chaining scopes impossible.  Anyone have insight on this?

```
class Product < ActiveRecord::Base
  include IdentityCache
  # visible is a boolean field on Product 
  cache_index :visible

   scope :visible, -> { fetch_by_visible(true) }
end


# in controller code, the following query returns an array
products = Product.visible
```

**Comment by dylanahsmith** [comment]
> Returning an array makes chaining scopes impossible.

If you want an active record scope, then use active record.  Identity cache can't cache arbitrary queries, since it needs to know about the queries ahead of time to be able to invalidate their results through after_commit hooks.  So returning an array is by design to reflect the limitations of the caching strategy this library uses.
