### ISSUE TITLE
ActiveRecord::RecordNotFound is raised, but record is exist in database

### ISSUE THREAD

**Issue by saiqulhaq** [Shopify/identity_cache#422]
as the title, why raise ActiveRecord::RecordNotFound if my record in database is exist?

my stack:
Rails 5.0, MySQL 5.7 in AWS

**Comment by saiqulhaq** [comment]
caused by this line https://github.com/Shopify/identity_cache/blob/8f68b3df84e03a4e966a82795edb530f03e79f42/lib/identity_cache/query_api.rb#L45

**Comment by rafaelfranca** [comment]
@dylanahsmith @gmcgibbon maybe we should raise an specific exception that inherits from RecordNotFound just to make clear?

**Comment by gmcgibbon** [comment]
👍

**Comment by saiqulhaq** [comment]
this issue is happening again, I am pointing github master in my Gemfile (identity_cache-0cbe7ec09516)

it says that `IdentityCache::RecordNotFound will be raised if id is not in the cache or the db.`

https://github.com/Shopify/identity_cache/blob/0cbe7ec09516569f79fdee7a3ac25c9e16084229/lib/identity_cache/with_primary_index.rb#L113

but the reality is like this
![image](https://user-images.githubusercontent.com/1275215/72496006-dc275a00-385a-11ea-8b31-4ea31c5341ff.png)

**Comment by gmcgibbon** [comment]
Oh, right. I need to update the docs to demonstrate the new behaviour. `IdentityCache::RecordNotFound` is raised for no cache entry, and `ActiveRecord::RecordNotFound` is raised for no db entry. Thanks for pointing that out!

**Comment by dylanahsmith** [comment]
It sounds like `nil` might have been cached for the record and then not invalidated by the creation of that record.

It is hard to say why the cache wasn't invalidated, but make sure to pay attention to the configuration in the installation section of the README to avoid using a cache backend that doesn't have CAS support and to avoid the `auto_eject_hosts: true` memcached client configuration.  Otherwise, logging might be the best way to try to track down why the cache invalidation might have been lost.

The other question is why the id was being queried before the transaction that created it was committed.  One possibility would be a client that tried to probe for records with different ids, such as to look for an Insecure Direct Object References (IDOR) vulnerability.  However, a more likely reason might be that the id was shared before the transaction actually committed, such by enqueuing a background job that references the record id within the transaction that creates it (e.g. using an `after_create` callback).  It is best to avoid making any requests to other datastores within a transaction, which could be done by using an `after_commit` callback instead of `after_create`.

Let me know if that helps you track down you track down the source of the problem

**Comment by saiqulhaq** [comment]
it's not only happening on Sidekiq job

but also happening in rails console

as you could see right here
![72496006-dc275a00-385a-11ea-8b31-4ea31c5341ff](https://user-images.githubusercontent.com/1275215/72782783-2e9bb880-3c57-11ea-8180-252bc8ec5ec9.png)

```
Reservation.fetch xxx # not found
Reservation.find xxx # works
Reservation.fetch xxx # works
```

**Comment by dylanahsmith** [comment]
You are just showing that the cache is inconsistent with the database (i.e. it has cached `nil` for a record that is in the database), not how it became inconsistent.  Once the cache is inconsistent, then certainly you could see that in the rails console, background job or anywhere else, but you aren't providing any more information than about why the cache became inconsistent. There are multiple ways that could happen, as explained in my last comment.

**Comment by saiqulhaq** [comment]
OK thank you @dylanahsmith for your help

I will create new issue with detailed info if I found it
