### ISSUE TITLE
Clarify behavior with serializers

### ISSUE THREAD

**Issue by oyeanuj** [Shopify/identity_cache#444]
Hi @dylanahsmith @gmcgibbon, thanks for creating this library! I had a quick question on usage with serializers: I'm using [AMS](https://github.com/rails-api/active_model_serializers) and in my code, inevitably, the serializers ends up going to the DB for some use-cases. 

I'm curious if there is a way to have it instead look at the identity cache?

**Comment by dylanahsmith** [comment]
That sounds like an active model serializers question.  It looks like active record isn't a runtime dependency of active model serializers, so it shouldn't have any explicit coupling to active record.  So it just need to be able to decouple the names of the methods from the names in the serialized data.  If this doesn't work, then it sounds like it is an issue with active model serializers rather than this library.
