### ISSUE TITLE
How to convert where to fetch_

### ISSUE THREAD

**Issue by sahilpaudel** [Shopify/identity_cache#467]
My where code
```
def by_type(type)
        em = Cms::EntityMetadatum.where name: type
        Cms::Entity.where entity_metadatum: em
end
```

To fetch
```
def by_type(type)
        em = Cms::EntityMetadatum.fetch_by_name(type)
       Cms::Entity.where entity_metadatum: em
      end
```

How can I convert the second line as well.

**Comment by dylanahsmith** [comment]
It looks like you are querying an id field on the second line.  A lower-level way of doing the Active Record query would be `Cms::Entity.where entity_metadatum_id: em.id`.  Once you look at it that way, converting that second line to use Identity Cache is similar to the first one, where you just need a `cache_index :entity_metadatum_id, unique:` on `Cms::Entity` so that you can do `Cms::Entity.fetch_by_entity_metadatum_id(em.id)`
