### ISSUE TITLE
WithoutPrimaryIndex and cache_index

### ISSUE THREAD

**Issue by lucasklaassen** [Shopify/identity_cache#491]
Is it by design that you cannot use `cache_index` when you include `IdentityCache::WithoutPrimaryIndex`?

Since we have a multi-tenant application, we would like to replace the default index with a `cache_index :id, :tenant_id` but it appears that `cache_index` isn't included within the model when using `WithoutPrimaryIndex`

**Comment by dylanahsmith** [comment]
`cache_index` uses the primary index to load the record, so by design it depends on the primary index.  If you want that behaviour, then just use `include IdentityCache` instead.

It sounds like you just want to filter the record by `tenant_id`, which can be done using a helper methods.  For example you could extend your models with a module like this

```
module IdentityCacheFetchByTenantIdAndId
  def fetch_by_tenant_id_and_id(tenant_id, id)
    record = fetch_by_id(id)
    return nil if record && record.tenant_id != tenant_id
    record
  end

  def fetch_by_tenant_id_and_id!(tenant_id, id)
    fetch_by_tenant_id_and_id(tenant_id, id) || raise(ActiveRecord::RecordNotFound)
  end

  def fetch_multi_by_tenant_id_and_id(tenant_id, ids)
    records = fetch_multi(ids)
    records.select { |record| record.tenant_id == tenant_id }
  end
end
```
