### ISSUE TITLE
has_many cache returning raw cache entries on subsequent loads

### ISSUE THREAD

**Issue by xxx** [Shopify/identity_cache#69]
Hello,

I have a has_many cache defined in an object -

    has_many :tags
    cache_has_many :tags

In a Rails console, I test this out (starting with an empty cache)

    ob = MyModel.find(1).fetch_tags # correctly queries the db and returns the results
    ob.fetch_tags # correctly *doesn't* query the db, and returns array of cached results

if I reload this object after it has populated its cache, however, I get raw cache entries instead -

    MyModel.find(1).fetch_tags # correctly queries the db and returns the results
    MyModel.find(1).fetch_tags # correctly does not query the db, but returns array of ActiveSupport::Cache::Entry objects

This same phenomenon happens when hitting an endpoint in a browser as well - the first load returns correct results, but raw cache entries are returned on all subsequent requests.

This is happening in my dev environment (rails_env == :development), using the master branch pulled from github a couple of hours ago.

**Comment by dylanahsmith** [comment]
@tjoyal your example doesn't demonstrate the issue. The `fetch_` method for a has_many association should return an Array so that it isn't used for chaining.  E.g. `blog.fetch_comments.where(approved: true)` could result in `fetch_comments` loading the comments followed by a subsequent database query with the added where condition.

The issue was that an Array of `ActiveSupport::Cache::Entry` objects was being returned.  Is this still an issue?

**Comment by tjoyal** [comment]
Could not reproduce the same state as my comment. I'd say it's no longer an issue for me. I'll add more information id I ever hit the issue again.

**Comment by dylanahsmith** [comment]
@xxx is this still an issue?
